volumes:
  mos-data:
    external: true
services:
  react:
    command: /bin/bash run.sh
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
    image: node:lts-bullseye
    ports:
    - 3000:3000
    volumes:
    - ./frontend:/app
    working_dir: /app
  api:
    build:
      dockerfile: Dockerfile.dev
    environment:
      MONGOHOST: mongo
      MONGODATABASE: mosdata
      MONGOUSER: mosdata
      MONGOPASSWORD: mosdata
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  mongo:
    image: mongo:6-jammy
    volumes:
      - mos-data:/dat/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mosdata
      MONGO_INITDB_ROOT_PASSWORD: mosdata
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mosdata
      ME_CONFIG_MONGODB_ADMINPASSWORD: mosdata
      ME_CONFIG_MONGODB_URL: mongodb://mosdata:mosdata@mongo:27017/
    restart: always


